name: xgboost-example
channels:
  - conda-forge
  - default
dependencies:
  - python=3.8
  - pip
  - pip:
      - mlflow>=1.6.0
      - scipy
      - scikit-learn
      - matplotlib
      - xgboost
      - boto3
